### ISSUE TITLE
Implementation checklist (WIP)

### ISSUE THREAD

**Issue by gedankenexperimenter** [gedankenlab/Kaleidoglyph-Glukeys#4]
### Basic functionality

- [x] Look up `Key` value from `glukeys_` array and set it appropriately when a `GlukeysKey` is pressed
- [x] Make glukeys `sticky` after a single press
- [x] Make all `sticky` keys release after a subsequent key tap
- [x] Make `sticky` keys become `locked` after a second tap
- [x] Make `locked` keys release after another tap
- [x] `sticky` keys should not release after another `glukey` is tapped
- [x] `pending` keys should become `normal` (i.e. non-sticky) when another non-glukey is tapped

### User-optional functionality

- [x] Activate/deactivate plugin
- [x] Automatically treat modifiers as glukeys
- [x] Automatically treat layer-shift keys as glukeys
- [x] Simpler `GluKey` type for basic keycodes (without storing in external array; all info stays in keymap)
- [ ] Allow users to specify "lockable" keys _à la_ OneShot's "stickability", probably by `Key` type (modifiers | layer changers | other keys), but maybe by glukey index value
- [x] Configurable glukeys ttl(s)
- [x] Let meta-glukey lock keys, rather than making them sticky first

### Possible improvements

- [x] Layer shifts & modifiers should not become `trigger` keys, even if they're not glukeys
- [x] Layer lock keys should not become `trigger` keys
- [x] Special `GlukeysKey` value (`cMetaGlukey`?) that makes other keys sticky when pressed
- [x] `cMetaGlukey` should have the same stickiness properties as other glukeys, but should cancel itself (when `sticky`) as soon as another key is pressed, but it should only cancel _itself_, not all `sticky` keys.
- [x] Special `Key` for cancelling all glukeys (both `sticky` and `locked`)
- [x] Store `glukeys_` array in `PROGMEM`
